name: deploy-surge
on: push
jobs:
  deploy-surge:
    name: Deploy on Surge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Deploy to Surge
        run:  npm run deploy --token ${{secrets.SURGE_TOKEN}}